name: Deploy to Cloudflare Pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    if: github.repository != 'RankAndRentWeb/plantilla-base'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2ce4541fb8e609f8b8206eb73175ae67
          command: pages deploy out --project-name=${{ github.event.repository.name }}
